version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"
    ports:
      - "2181:2181"
    networks:
      - dlts-net

  kafka-broker-1:
    image: confluentinc/cp-kafka:latest
    depends_on: 
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "register:2:1,test_config:2:1,trigger:2:1,metrics:2:1,test_topic:2:1,heartbeat:2:1"
    ports:
      - "9093:9093"
    networks: 
      - dlts-net

networks:
  dlts-net:
